# Generated by Django 3.2.8 on 2021-10-12 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 19, 15, 54, 224047)),
        ),
    ]
