# Generated by Django 3.2.8 on 2021-10-12 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alter_todos_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 19, 16, 52, 482208, tzinfo=utc)),
        ),
    ]
