# Generated by Django 3.2.8 on 2021-10-12 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_alter_todos_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
