# Generated by Django 3.2.8 on 2021-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_rename_todos_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='completed_at',
            field=models.DateTimeField(default=None),
        ),
    ]
