# Generated by Django 3.2.8 on 2021-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0007_auto_20211012_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='Incomplete', max_length=10),
        ),
    ]
